---
title: "CleaningData"
output: html_document
---

Load packages

```{r}
library(dplyr)
```

Load x train data

```{r, cache=TRUE}
setwd("~/Documents/CourseraDS/UCI HAR Dataset")
train_x <- read.table("train/x_train.txt")

```

Load y train and subject data

```{r, cache=TRUE}
train_y <- read.table("train/y_train.txt")
train_sub <- read.table("train/subject_train.txt")
```

Load features

```{r}
feature_name <- read.table("features.txt")
```

rename train

```{r}
names(train_x) <- feature_name[,2]
names(train_y) <- "Activity_Index"
names(train_sub) <- "Subject_Index"
train_x <- train_x[,grep("mean()|std()",colnames(train_x))]
train_info <- bind_cols(train_y,train_sub)
train_all <- bind_cols(train_info,train_x)

```



Load x test data

```{r, cache=TRUE}

test_x <- read.table("test/x_test.txt")

```

Load y test and subject data

```{r, cache=TRUE}
test_y <- read.table("test/y_test.txt")
test_sub <- read.table("test/subject_test.txt")
```

rename test

```{r}
names(test_x) <- feature_name[,2]
names(test_y) <- "Activity_Index"
names(test_sub) <- "Subject_Index"
test_x <- test_x[,grep("mean()|std()",colnames(test_x))]
test_info <- bind_cols(test_y,test_sub)
test_all <- bind_cols(test_info,test_x)

```


Union test and train

```{r}
data <- bind_rows(train_all,test_all)
```


Load activity

```{r}
activity_labels <- read.table("activity_labels.txt")
names(activity_labels) <- c("Activity_Index","Activity_Label")
head(activity_labels)
```

Join in activity name

```{r, results='hide'}
data <- full_join(activity_labels,data,by = "Activity_Index")
data <- select(data,-Activity_Index)
data %>% group_by(Activity_Label,Subject_Index) %>% summarise_each(funs(mean))
```

Summary
```{r}
head(data)
```
